modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "vrapi"
version = "${version}"
displayName = "mc-vr-api"
authors = "hammy3502"
description = '''
VR API mod that allows mods to integrate into Vivecraft.
'''
#logoFile = ""

[[dependencies.vrapi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"