modLoader = "javafml"
loaderVersion = "[44,)"
#issueTrackerURL = ""
license = "GNU GPLv3"

[[mods]]
modId = "vrapi"
version = "2.1.1"
displayName = "mc-vr-api"
authors = "hammy3502"
description = '''
VR API mod that allows mods to integrate into Vivecraft.
'''
#logoFile = ""

[[dependencies.vrapi]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vrapi]]
modId = "architectury"
mandatory = true
versionRange = "[7.0.66,)"
ordering = "AFTER"
side = "BOTH"